export const GAMEPLAY_CONSTANTS = {
  WORLD_WIDTH: 1280,
  WORLD_HEIGHT: 960,
  PLAYER_MAX_HP: 100,
  PLAYER_SPEED: 160,
  ATTACK_RANGE: 42,
  ATTACK_DAMAGE: 10,
  ATTACK_COOLDOWN_MS: 250,
  RESOURCE_RESPAWN_MS: 8_000,
  CREATURE_RESPAWN_MS: 12_000,
  CREATURE_PATROL_RANGE: 120,
  CREATURE_PATROL_SPEED: 40,
  INVENTORY_MAX_SLOTS: 20
} as const;

export enum ItemType {
  Wood = "WOOD",
  Essence = "ESSENCE"
}
